# golangci-lint configuration
# Docs: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25"

linters:
  enable:
    - errcheck       
    - gosimple       
    - govet          
    - ineffassign    
    - staticcheck    
    - unused         
    - gofmt          
    - goimports      
    - misspell       
    - revive         
    - gocritic       

linters-settings:
  goimports:
    local-prefixes: github.com/BeInBloom/grpc-chat

  revive:
    rules:
      - name: exported
        disabled: true  

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
